steps:
  # Step 1: Build the Docker image from your Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/air-quality-repo/aq-pipeline-image:latest', 
      '.'
    ]

  # Step 2: Push the compiled image into your Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'asia-south1-docker.pkg.dev/$PROJECT_ID/air-quality-repo/aq-pipeline-image:latest'
    ]

  # Step 3: Update the Cloud Run Job configuration to use the fresh container image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'jobs', 'update', 'aq-hourly-fetch-job',
      '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/air-quality-repo/aq-pipeline-image:latest',
      '--region', 'asia-south1'
    ]

options:
  logging: CLOUD_LOGGING_ONLY